# -*- coding: utf-8 -*-
"""assignment1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SUHUPFaL4ByPx-Smk28H1DkrgL4Yfr-3
"""

import pandas as pd
import numpy as np
from prophet import Prophet

data = pd.read_csv("https://github.com/dustywhite7/econ8310-assignment1/raw/main/assignment_data_train.csv")

trips = data[['Timestamp','trips']]

trips['Timestamp'] = pd.to_datetime(trips['Timestamp'])

trips = pd.DataFrame(trips.values, columns = ['ds','y'])

model = Prophet(changepoint_prior_scale=0.5)

modelFit = model.fit(trips)

future = model.make_future_dataframe(freq = 'h', periods=744)
predData = model.predict(future)

pred = predData['yhat'].values[-744:]

pred